# Generated by Django 5.0.1 on 2024-02-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Оператор')),
                ('inn', models.IntegerField(default=0, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторs',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('abc_def', models.IntegerField(default=0, verbose_name='АВС/DEF')),
                ('sn_from', models.IntegerField(default=0, verbose_name='От')),
                ('sn_to', models.IntegerField(default=0, verbose_name='До')),
                ('capacity', models.IntegerField(default=0, verbose_name='Емкость')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Диапазон',
                'verbose_name_plural': 'Диапазонs',
                'unique_together': {('abc_def', 'sn_from', 'sn_to')},
            },
        ),
    ]
