# Generated by Django 5.0.1 on 2024-02-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='inn',
            field=models.BigIntegerField(default=0, verbose_name='ИНН'),
        ),
    ]
