# Generated by Django 5.0.1 on 2024-02-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_operator_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.AlterField(
            model_name='range',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.region', verbose_name='Регион'),
        ),
    ]
