# Generated by Django 5.0.1 on 2024-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_rename_title_operator_name_rename_title_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=1500, verbose_name='Регион'),
        ),
    ]
